version: "3"
services:
  squid-alpine-ssl:
    build: ./
    image: oiprnd/squid-alpine-ssl:latest
    environment:
      - CN=squid.oip
      - O=OIP
      - OU=Labs
      - C=FR
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
    restart: always
